#!/bin/bash
source $HOME/.config/zdm/way/Wsession

export XDG\_CURRENT\_DESKTOP=sway  
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

#exec dbus-run-session sway --unsupported-gpu  
exec sway --unsupported-gpu  
