#!/bin/sh
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export MOZ_ENABLE_WAYLAND=1
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export WLR_BACKEND=vulkan
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=x11
export GDK_BACKEND=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM=wayland
export MOZ_DBUS_REMOTE=1
export _JAVA_AWT_WM_NONREPARENTING=1
#experimental 
export LIBVA_DRIVER_NAME=nvidia
export WLR_DRM_NO_ATOMIC=1
export XCURSOR_SIZE=24
export WLR_RENDERER=vulkan # vulkan brakes dolphin-emu(Xwayland) gui and brakes steam XCURSOR but is worth it for the removal of a bug in Xorg apps on Wayland nvidia games
#export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json
export WLR_XWAYLAND="$XDG_CONFIG_HOME/Xwayland/Xwayland"
