#!/bin/sh
xfce="0"
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &


~/.fehbg


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Gimp desktop='^8' follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# zuki rules
#bspc rule -a Steam desktop='^4'
#bspc rule -a heroic desktop='^4'
bspc rule -a epicgameslauncher.exe state=floating

# xfce
if [ "$xfce" = "1" ]
then
	pgrep -x xfce4-panel > /dev/null || xfce4-panel -d &
	bspc rule -a xfce4-panel layer=above
fi
