#!/bin/sh

systemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
   dbus-update-activation-environment DISPLAY XAUTHORITY
fi
#systemctl --user import-environment DISPLAY XAUTHORITY
#if command -v dbus-update-activation-environment >/dev/null 2>&1; then
#    dbus-update-activation-environment DISPLAY XAUTHORITY
#fi
xsetroot -cursor_name left_ptr
polkit-dumb-agent &
