#!/bin/sh
# this file sets vars then starts river.
# Vars
cursorSize=30
iconTheme='Arc'
gtkTheme='Arc-Dark'
cursorTheme='Adwaita'
XCURSORTHEME=$cursorTheme

# Exports
export QT_QPA_PLATFORMTHEME=qt5ct:qt6ct
export MOZ_ENABLE_WAYLAND=1 
export XDG_CURRENT_DESKTOP=river
# export ELECTRON_OZONE_PLATFORM_HINT=auto

# this is optional and probably pointless
export XDG_SESSION_TYPE=wayland

#nvidia
export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export NVD_BACKEND=direct
# somehow I get graphical bugs with electron apps when running with pure wayland but none when running them in xorg mode
# weird.
export ELECTRON_OZONE_PLATFORM_HINT=x11

export __GLX_VENDOR_LIBRARY_NAME=nvidia
export XCURSORTHEME=$cursorTheme
export XCURSOR_SIZE=$cursorSize
# export HYPRCURSOR_SIZE=$cursorSize

# uncomment these two lines to get a headless virtual display
# export WLR_BACKENDS=drm,libinput,headless 
# export WLR_HEADLESS_OUTPUTS=1 

# for gentoo with openrc
# exec dbus-launch --exit-with-session river

# for nixos with systemd
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
exec river
