#!/bin/sh
# this file sets vars then starts river.
# Vars
cursorSize=34
iconTheme='Arc'
gtkTheme='Arc-Dark'
cursorTheme='Adwaita'
XCURSORTHEME=$cursorTheme

# Exports
export QT_QPA_PLATFORMTHEME=qt5ct:qt6ct
export MOZ_ENABLE_WAYLAND=1 
export XDG_CURRENT_DESKTOP=river
# export XCURSORTHEME=$cursorTheme
# export XCURSOR_SIZE=$cursorSize
# export HYPRCURSOR_SIZE=$cursorSize
exec dbus-launch --exit-with-session river
